package com.example.atmos.ui.theme

import androidx.compose.ui.graphics.Color


val WeatherCyan   = Color(0xFF48CAE4)
val WeatherViolet = Color(0xFF8A6FFF)
val WeatherNavy   = Color(0xFF0B1120)

val White       = Color(0xFFFFFFFF)

val PrimaryLight            = Color(0xFF030213)
val BackgroundLight1        = Color(0xFFF0F4FF)
val BackgroundLight2        = Color(0xFFE8EEFF)
val TextPrimaryLight        = Color(0xFF1A1A2E)
val CardLight               = Color(0xFFFFFFFF)
val MutedLight              = Color(0xFFECECF0)
val MutedForegroundLight    = Color(0xFF717182)
val InputBackgroundLight    = Color(0xFFF3F3F5)
val SwitchBackgroundLight   = Color(0xFFCBCED4)
val BorderLight             = Color(0x1A000000)
val DestructiveLight        = Color(0xFFD4183D)

val PrimaryDark             = Color(0xFFFAFAFA)
val BackgroundDark          = Color(0xFF0B1120)
val BackgroundDark2         = Color(0xFF1A1040)
val TextPrimaryDark         = Color(0xFFFFFFFF)
val CardDark                = Color(0xFF0B1120)
val MutedDark               = Color(0xFF262626)
val MutedForegroundDark     = Color(0xFF8F8F9E)
val BorderDark              = Color(0xFF262626)
val InputDark               = Color(0xFF262626)
val DestructiveDark         = Color(0xFF7F1D1D)
val DestructiveFgDark       = Color(0xFFFCA5A5)

val DayCardBackground       = Color(0xFFFA7833).copy(alpha = 0.4F)
val DayCardBorder           = Color(0x55FFFFFF)
val DayTextPrimary          = Color(0xFFFFFFFF)
val DayTextSecondary        = Color(0xCCFFFFFF)
val DayTextMuted            = Color(0x99FFFFFF)
val DayTextHint             = Color(0x77FFFFFF)
val DaySectionTitle         = Color(0xFF1A1A2E)
val DayIconTint             = Color(0xFF48CAE4)
val DayTempBarBackground    = Color(0x33FFFFFF)
val DayTempBarFillStart     = Color(0xFF48CAE4)
val DayTempBarFillEnd       = Color(0xFF0077B6)
val DayActiveDot            = Color(0xFFFF6B35)

val NightCardBackground       = Color(0x40FFFFFF)
val NightCardBackgroundStrong = Color(0x4DFFFFFF)
val NightCardBorder           = Color(0x40FFFFFF)
val NightTextPrimary          = Color(0xFFFFFFFF)
val NightTextSecondary        = Color(0xCCFFFFFF)
val NightTextMuted            = Color(0x99FFFFFF)
val NightTextHint             = Color(0x77FFFFFF)
val NightSectionTitle         = Color(0xFFFFFFFF)
val NightIconTint             = Color(0xFF48CAE4)
val NightTempBarBackground    = Color(0x33FFFFFF)
val NightTempBarFillStart     = Color(0xFF48CAE4)
val NightTempBarFillEnd       = Color(0xFF8A6FFF)
val NightActiveDot            = Color(0xFFFF6B35)

val AlertCritical = Color(0xFFFF6B6B)
val AlertWarning  = Color(0xFFFFD93D)
val AlertInfo     = Color(0xFF48CAE4)
val AlertSuccess  = Color(0xFF6BCB77)